[package]
name = "sarcspeak"
version = "0.1.0"
authors = ["AviusX <aviusanima@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copypasta-ext = "0.3.4"
